name: "DevSecX_workflow"
description: "Scan the current repository's source code, send it to the LLM API using built-in API credentials, and upload the API response as an artifact."
runs:
  using: "composite"
  steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install required packages
      shell: bash
      run: |
        pip install --upgrade pip
        pip install requests

    - name: Run source code scan and LLM API request
      shell: bash
      run: |
        python devsecx_workflow/scan_llm.py

    - name: Upload LLM API Response Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: llm-response
        path: response.txt
