name: "DevSecX_workflow"
description: "Scan the current repository's source code, send it to the LLM API using built-in API credentials, and upload the API response as an artifact."
runs:
  using: "composite"
  steps:
    # 1. 호출한 리포지토리 체크아웃
    - name: Checkout current repository
      uses: actions/checkout@v3

    # 2. DevSecX_workflow 리포지토리 체크아웃
    - name: Checkout DevSecX_workflow repository
      uses: actions/checkout@v3
      with:
        repository: avox-dev/DevSecX_workflow
        ref: main
        path: devsecx_workflow

    # 3. Python 설정
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # 4. 필수 패키지 설치
    - name: Install required packages
      shell: bash
      run: |
        pip install --upgrade pip
        pip install requests groq bandit

    # 5. 스크립트 실행 후 파일 존재 확인
    - name: Run source code scan and LLM API request
      shell: bash
      env:
        MY_API_KEY: ${{ env.MY_API_KEY }}
      run: |
        python devsecx_workflow/scan_llm.py --api-key "$MY_API_KEY"
        echo "Checking if response.txt exists..."
        ls devsecx_workflow -al

    # 6. 결과 아티팩트 업로드 (파일 경로 확인 후 수정)
    - name: Upload LLM API Response Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: llm-response
        path: devsecx_workflow/response.txt
