# .github/actions/my-workflow-module/action.yml
name: "DevSecX_workflow"
description: "A reusable composite action for common CI tasks."
inputs:
  python-version:
    description: "Python version to set up."
    required: false
    default: "3.12"
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        pip install bandit bandit-sarif-formatter